Repository leonleerl/cits5505-tournament-management-system, pull requests merged in 2025-05, with the labels that each got.

#21 #19 Validation for login and forgot password page
  forgotpassword.html
  js/login.js
Labels: enhancement, backend

#35 26 landing page clarify fantasy basketball use case
  app.py
  app/routes/main_routes.py
  app/static/css/index.css
  app/static/js/index.js
  app/templates/base.html
  app/templates/index.html
  recreate_db.py
  seed_db.py
Labels: enhancement, frontend, backend

#49 48 quality of life automatic pycache cleanup on application shutdown
  app.py
  recreate_db.py
  test_app.py
  test_imports.py
Labels: cleanup

#52 45 GitHub update app launch instructions
  app.py
  app/static/css/index.css
  app/templates/index.html
  config.py
  seed_db.py
Labels: frontend, backend

#63 47 generate /db folder automatically for database initialisation
  app.py
Labels: backend
